trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  strategy:
    maxParallel: 1  # Limite la concurrence des instances de ce job
  steps:
  - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
    displayName: 'Custom Checkout Task'
    inputs:
      repository: self
      fetchDepth: 1
